version: "3"
services:
    client:
        build:
            context: .
        image: ${DOCKER_USERNAME}/integrated-tracker
        environment:
            - WATCHPACK_POLLING=true
            # - CHOKIDAR_USEPOLLING=true
            # - WDS_SOCKET_HOST=127.0.0.1
            - "GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}"
            - "GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}"
            - "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}"
        ports:
            - "3000:${LOCAL_CLIENT_PORT}"
        # volumes:
        #     - .:/app
        #     - ./node_modules:/app/node_modules
        #     - ./.next:/app/.next
        develop:
            watch:
                - action: sync
                  path: ./src
                  target: /app/src
                  ignore:
                      - node_modules
                - action: rebuild
                  path: package.json

    mongodb:
        image: mongo
        attach: false
        # restart: always
        # environment:
        #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        #   MONGO_INITDB_DATABASE: ${DB_NAME}
        # expose:
        #   - 27017
        ports:
            - ${DB_PORT}:27017
        volumes:
            - ./db:/data/db:rw
